import type { NextPage } from "next";
import Head from "next/head";
import Section from "../components/organisms/Section";
import HelloMain from "../components/molecules/HelloMain";
import About from "../components/organisms/About";
import ProjectCard from "../components/molecules/ProjectCard";
import Title from "../components/atoms/Title";
import Contact from "../components/organisms/Contact";
import projects from "./../public/projects.json"
const Home: NextPage = () => {
  return (

    <div>
      <Head>
        <title>ArZi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>


      {/* Hello section, black screen on top of page */}
      <Section className="main-section">
        <HelloMain title="Hey, I'm ArZi">
          Dedicated web dev. Faithful to Next.js. Good friend with Python. <br /> Technology geek
        </HelloMain>
      </Section>


      {/* Section describing me with profile icon and three paragraphs */}
      <Section className="about-section">
        <a id="about"></a>
        <About/>
        <a id="projects" style={{position:"relative",top:"-50px"}}></a>
      </Section>


      {/* Project section in grid-like styling */}
      <Section className="projects-section">

        {/* Header for project section */}
        <div className="projects__desc">
          <Title className="projects__header--title">Projects</Title>
          <div className="projects__header--text">Check out my <a href="https://github.com/ArziPL?tab=repositories" target="_blank" rel="noreferrer">GitHub</a> for all of them or click on one !</div>
        </div>

        {/* All project cards - rendered from json file public/projects.json */}
        <div className="projects__cards">
          {projects.map((project) => (
            <ProjectCard key={project.id}  name={project.name} bgColor={project.bgColor} link={project.link}>{project.desc}</ProjectCard>
          ))}
          </div>
      </Section>


      {/* Small contact section with links and quote */}
      <Section className="contact-section">
        <a id="contact"></a>
        <Contact/>
      </Section>


    </div>
  );
};

export default Home;
