import type { NextPage } from "next";
import Head from "next/head";
import Section from "../components/organisms/Section";
import HelloCard from "../components/molecules/HelloCard";
import AboutTemplate from "../components/organisms/AboutTemplate";
import ProjectCard from "../components/molecules/ProjectCard";
import Title from "../components/atoms/Title";
import FooterCard from "../components/organisms/FooterCard";
import { relative } from "path";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ArZi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>

      <Section className="section main">
        <HelloCard title="Hey, I'm ArZi">
          Dedicated web dev. Faithful to Next.js. Good friend with Python. <br /> Technology geek
        </HelloCard>
      </Section>

      <Section className="section about">
        <a id="about"></a>
        <AboutTemplate/>
        <a id="projects" style={{position:"relative",top:"-50px"}}></a>
      </Section>
      <Section className="section projects">
        <div className="projects__desc">
        <Title className="projects__desc--title">Projects</Title>
        <div className="projects__desc--desc">Check out my <a href="https://github.com/ArziPL?tab=repositories" target="_blank" rel="noreferrer">GitHub</a> for all of them or click on one !</div>
        </div>
        <div className="projects__wrapper">
          <ProjectCard bgColor="#E05F5B" name="space-next" link="https://github.com/ArziPL/space-next">
            Responsive site displaying two dynamic lists with data acquired from SpaxeX REST API, done in Next.js, styled in SCSS
          </ProjectCard>
          <ProjectCard bgColor="#65A4D9" name="hello-mern" link="https://github.com/ArziPL/hello-mern">
            App letting you log in, register, show all users or delete any of them while updating all data constantly in MongoDB using Express.js server. Front-end done in clear React.
          </ProjectCard>
          <ProjectCard bgColor="#F9F2D5" name="crypto-articles-api" link="https://github.com/ArziPL/crypto-articles-api">
              Flask API which scrapes and returns cryptocurrency news, for the project Exchange.
          </ProjectCard>
          <ProjectCard bgColor="#F3E8AD" name="exchange" link="https://github.com/ArziPL/exchange">
            [IN PROGRESS] Cryptocurrency market app containing functions such as listing cryptocurrencies, showing detailed data about a given cryptocurrency or news from the world of cryptocurrencies.
          </ProjectCard>
          <ProjectCard bgColor="#5A637F" name="dsapp" link="https://github.com/ArziPL/dsapp">
            All data structures, algorithms and programming problems which I have studied and tried to understand. All files are in Python, in most cases documented and ready to use.
          </ProjectCard>
          <ProjectCard bgColor="#48767A" name="lux-moto" link="https://github.com/ArziPL/lux-moto">
            My first project in React, written in old class components. Also first time used SCSS. Project at the moment is not possible to run due to old dependencies.
          </ProjectCard>
          <ProjectCard bgColor="#E8E8E9" name="is-your-password-safe" link="https://github.com/ArziPL/is-your-password-safe">
            Script checking how many times your password leaked/was breached using haveibeenpwned.com API and good old Python.
          </ProjectCard>
          <ProjectCard bgColor="#A0D988" name="30-tweets" link="https://github.com/ArziPL/30-tweets">
            Python script printing in console last 30 tweets of any user (default Eminem) using Twitter API.
          </ProjectCard>
          </div>
      </Section>
      <Section className="section footer">
        <a id="contact"></a>
        <FooterCard/>
      </Section>
    </div>
  );
};

export default Home;
